Updated loop Need testing
QBCore-Remastered/qb-weapons pull request #2
Opened 2022-10-02 20:12 UTC by JericoFX

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

This pr delete a loop and add a low game event, this handle the UpdateWeaponAmmo and quality of the weapon.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? ++yes++
- Does your code fit the style guidelines? i think
- Does your PR fit the contribution guidelines? ++yes++

2022-10-04 16:47 UTC, JericoFX commented on client/main.lua
> +    if player == ped then --have to do this because the event is fired by the amount of people who saw the player shoot, so if 100 npc hear you shoot, this will trigger 100 times
i dont know if this is necessary, the code is client side...

2022-10-08 15:54 UTC, D4isDAVID commented
Nice PR, I've made a PR to improve upon it (JericoFX#1).

2022-10-10 01:42 UTC, D4isDAVID requested changes

2022-10-10 01:42 UTC, D4isDAVID commented on client/main.lua
>  local shootingThread = 500
```suggestion
local shootingThread = 500
```
Unnecessary comment, we don't need to keep this.

2022-10-10 01:44 UTC, D4isDAVID approved these changes

2022-10-10 01:47 UTC, D4isDAVID commented on client/main.lua
> +    if player == ped then --have to do this because the event is fired by the amount of people who saw the player shoot, so if 100 npc hear you shoot, this will trigger 100 times
It is, at least obviously when not used by an exploiter.
The events used here (`weapons:server:UpdateWeaponAmmo` and `weapons:server:UpdateWeaponQuality`) are already exploitable on their own, so it doesn't matter much if this event is unsafe.

2022-10-10 01:49 UTC, Manason commented
Is this PR a refactor only, or is it added a new behavior? It's a bit unclear from the description.

2022-10-10 01:51 UTC, D4isDAVID commented
@Manason
This PR refactors code inside of what previously was a loop, into an event, to be more performant.

2022-10-10 02:34 UTC, Manason approved these changes

2022-10-10 02:34 UTC, Manason commented on client/main.lua
> +    if witnesses[1] ~= ped then return end
Consider combining these two if statements using an 'and' since they have the same outcome.

2022-10-10 02:34 UTC, Manason commented on client/main.lua
> +---@param witnesses table  array of peds that witnessed the shots
What defines a witness?

2022-10-10 02:35 UTC, D4isDAVID commented on client/main.lua
> +---@param witnesses table  array of peds that witnessed the shots
I'm think it should be a ped that heard the shot

2022-10-10 02:41 UTC, Manason commented on client/main.lua
> +---@param witnesses table  array of peds that witnessed the shots
What defines a ped that "hears" the shot?

2022-10-10 02:45 UTC, D4isDAVID commented on client/main.lua
> +---@param witnesses table  array of peds that witnessed the shots
A ped that can react to the shot, e.g. a running ped will witness the shot and run away

2022-10-10 02:47 UTC, Manason commented on client/main.lua
> +---@param witnesses table  array of peds that witnessed the shots
Ah. A native GTA behavior, got it.

2022-10-10 04:42 UTC, merged